### ISSUE TITLE
有些歌提示错误

### ISSUE THREAD

**Issue by 1124714647** [MeoProject/lx-music-api-server#54]
格式化错误失败，使用默认格式
Traceback (most recent call last):
  File "main.py", line 156, in handle
  File "modules\__init__.py", line 93, in url
  File "modules\kg\player.py", line 19, in url
KeyError: 'audio_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "common\log.py", line 115, in highlight_error
ValueError: 156 is not in list
2024-05-07 13:38:16|[main/ERROR]|
Traceback (most recent call last):
  File "main.py", line 156, in handle
  File "modules\__init__.py", line 93, in url
  File "modules\kg\player.py", line 19, in url
KeyError: 'audio_info'

**Comment by ikun0014** [comment]
这个问题我目测是hash不对

**Comment by ikun0014** [comment]
这首在企鹅是数专，我开了SVIP

**Comment by 1124714647** [comment]
是我的锅 都开了SVIP都OK了
