### ISSUE TITLE
/script 无法下载脚本

### ISSUE THREAD

**Issue by BnqDzj** [MeoProject/lx-music-api-server#55]
启动服务器后，/script无法下载脚本，直接返回502 Bad gateway

日志
```
格式化错误失败，使用默认格式
Traceback (most recent call last):
  File "main.py", line 110, in handle_request
  File "common/lx_script.py", line 90, in generate_script_response
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "common/log.py", line 115, in highlight_error
ValueError: 110 is not in list
2024-05-13 02:06:40|[main/ERROR]|
Traceback (most recent call last):
  File "main.py", line 110, in handle_request
  File "common/lx_script.py", line 90, in generate_script_response
TypeError: can only concatenate str (not "NoneType") to str

格式化错误失败，使用默认格式
Traceback (most recent call last):
  File "main.py", line 110, in handle_request
  File "common/lx_script.py", line 90, in generate_script_response
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "common/log.py", line 115, in highlight_error
ValueError: 110 is not in list
2024-05-13 02:06:54|[main/ERROR]|
Traceback (most recent call last):
  File "main.py", line 110, in handle_request
  File "common/lx_script.py", line 90, in generate_script_response
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by ikun0014** [comment]
系统环境：
Python版本：
问题如何复现：

**Comment by BnqDzj** [comment]
> 系统环境： Python版本： 问题如何复现：

系统环境：Debian 12
Python版本：直接二进制文件运行，无Python环境
问题如何复现：配置并开启请求key，启动后直接访问 /script?key=请求key

**Comment by ikun0014** [comment]
这边我推荐尝试按照文档clone部署，这个二进制文件我不确定是什么问题

**Comment by ikun0014** [comment]
主开发说：配置值common.download_config.intro为空
